// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicPlayerAvaloniaPort.Persistence.Database;

#nullable disable

namespace MusicPlayerAvaloniaPort.Migrations
{
    [DbContext(typeof(SongDbContext))]
    partial class SongDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("MusicPlayerAvaloniaPort.Persistence.Database.NotYetSyncedData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BelongedToSongId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NotYetSyncedData");
                });

            modelBuilder.Entity("MusicPlayerSyncInterface.DTOs.SongHistoryEntry", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SongId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("TEXT");

                    b.Property<float>("ScoreChange")
                        .HasColumnType("REAL");

                    b.HasKey("UserId", "SongId", "Date");

                    b.HasIndex("SongId");

                    b.ToTable("SongHistoryEntries");
                });

            modelBuilder.Entity("MusicPlayerSyncInterface.DTOs.UpvotedSong", b =>
                {
                    b.Property<Guid>("SongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Album")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Score")
                        .HasColumnType("REAL");

                    b.Property<int>("Streak")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalDislikes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalLikes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Volume")
                        .HasColumnType("REAL");

                    b.HasKey("SongId");

                    b.HasIndex("UserId", "Name", "Artist", "Album")
                        .IsUnique();

                    b.ToTable("UpvotedSongs");
                });

            modelBuilder.Entity("MusicPlayerSyncInterface.DTOs.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserDisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserHandle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MusicPlayerSyncInterface.DTOs.SongHistoryEntry", b =>
                {
                    b.HasOne("MusicPlayerSyncInterface.DTOs.UpvotedSong", "UpvotedSong")
                        .WithMany()
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UpvotedSong");
                });

            modelBuilder.Entity("MusicPlayerSyncInterface.DTOs.UpvotedSong", b =>
                {
                    b.HasOne("MusicPlayerSyncInterface.DTOs.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
